config/routes.rb
Codeandbeers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => {:registrations => "users", :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    get 'users/:id' => 'users#show', as: "user"
  end
  resources :users do 
    resources :helpful_links  
    resources :favourites  
  end
  
  root 'statics#home'
  
  resources :statics
  resources :events
  resources :collections
  resources :collection_links


  #Match Routes
  match '/about' => 'statics#about', via: 'get', as: 'about'
  match '/contact' => 'statics#contact', via: 'get', as: 'contact'
  match '/dashboard' => 'statics#dashboard', via: 'get', as: 'dashboard'
  match '/sitemap' => 'statics#sitemap', via: 'get', as: 'sitemap'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
belongs_to :user
belongs_to :helpful_link
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

	def index 
			
		@favourites = current_user.favourites
		@links = HelpfulLink.all

		@fav = Favourite.new
		@link = HelpfulLink.new
		@user = current_user
	end

	def new
		@fav = Favourite.new    
	end

	def create
		@fav = Favourite.new(fav_params)
		if @fav.save
			# RequestMailer.new_request_agents(@request, User.find(@request.user_id)).deliver
			flash[:notice] = "Added to favourites"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def destroy
		@fav.destroy
		respond_to do |format|
			format.html { redirect_to root_url }
			format.json { head :no_content }
		end
	end

	private

	# Never trust parameters from the scary internet, only allow the white list through.
	def fav_params
		params.require(:favourite).permit(:user_id, :helpful_link_id)
	end



end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_favourite_resources.html.erb
<% @favourites.each do |l| %>
<% @link = HelpfulLink.where(id: l.helpful_link_id).first %>



<%# @links.limit(30).order('created_at DESC').each do |l| %>

	<div class="well">
		<div class="row">
			<div class="col-md-10">
				<h4><%= link_to @link.name, @link.link %> <%= link_to "", edit_user_helpful_link_path(@link.user_id, @link.id), class: "fa fa-edit" unless @link.user_id != current_user.id %></h4>
			</div>
			<div class="col-md-2">
				<div class="favourite-link-form">
					<% if Favourite.where(helpful_link_id: @link.id).first.blank? %>
						<%= form_for [@user, @fav], remote: true do |f| %>
							<%= f.hidden_field :user_id, value: current_user.id %>
							<%= f.hidden_field :helpful_link_id, value: @link.id %>
							<button type='submit' class="favourite">
								<i class="fa fa-star favourite"></i>
							</button>
						<% end %>
					<% else %>
						<i class="fa fa-star favourited"></i>
					<% end %>
				</div>
			</div>
			<div class="col-md-12">
				<p><%= @link.description %></p>
				<p id="submitted">Submitted <% if User.where(id: @link.user_id).first %>by<%end%> <em><%= link_to User.where(id: @link.user_id).first.username, "", :data => {toggle: "modal", target: "#userModel#{@link.user_id}"}, id: "username" unless User.where(id: @link.user_id).first.blank? %></em> <%= time_ago_in_words(@link.created_at) %> ago.</p>
				<% if @link.paid == true %>
					<div class="label label-warning">
						<i class="fa fa-gbp"> Paid Resource</i>
					</div>
				<% else %>
					<div class="label label-success">
						<i class="fa fa-gbp"> Free Resource</i>
					</div>
				<% end %>
			</div>
		</div>
	</div>


	<% unless User.where(id: @link.user_id).blank? %>
		<!-- Show User -->
		<%= render 'shared/user_modal', locals: { user: User.find(@link.user_id) } %>
	<% end %>



<% end %>

app/views/favourites/index.html.erb
<%= render 'shared/global_meta_tags' %>

<div class="favourites-wrapper">
	
	<section>
		<div class="link-wrapper">	
			<h3><i class="fa fa-external-link"></i> Your Favourite Resources </h3>
			
				<%= render partial: 'favourites/favourite_resources'%>
		</div>
	</section>


</div>