config/routes.rb
Codeandbeers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => {:registrations => "users", :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    get 'users/:id' => 'users#show', as: "user"
  end
  resources :users do 
    resources :helpful_links  
    resources :favourites  
  end
  
  root 'statics#home'
  
  resources :statics
  resources :events
  resources :collections
  resources :collection_links


  #Match Routes
  match '/about' => 'statics#about', via: 'get', as: 'about'
  match '/contact' => 'statics#contact', via: 'get', as: 'contact'
  match '/dashboard' => 'statics#dashboard', via: 'get', as: 'dashboard'
  match '/sitemap' => 'statics#sitemap', via: 'get', as: 'sitemap'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/collection.rb
class Collection < ActiveRecord::Base

has_many :helpful_links, :through => :collection_links
has_many :collection_links

end

app/models/collection_link.rb
class CollectionLink < ActiveRecord::Base
belongs_to :helpful_link
belongs_to :collection
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :future, lambda { where("date >= ?", Date.today ) }
	scope :past, lambda { where("date < ?", Date.today ) }
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
belongs_to :user
belongs_to :helpful_link
end

app/models/helpful_link.rb
class HelpfulLink < ActiveRecord::Base
    
    # Associations
    belongs_to :user
    has_many :favourites
    has_many :collections, :through => :collection_links
	has_many :collection_links
    
    after_create :send_notification

    def send_notification
		AdminMailer.new_resource(self).deliver_now
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:twitter]

    has_many :helpful_links
    has_many :favourites
    after_create :send_notification

    validates_presence_of :username
    validates_uniqueness_of :username

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = auth.info.nickname
	    user.avatar = auth.info.image.sub("_normal", "")
	    # user.email = auth.info.email unless auth.info.email.blank?
	    # user.password = Devise.friendly_token[0,20]
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

	def send_notification
		AdminMailer.new_user(self).deliver_now
		UserMailer.new_user_welcome(self).deliver_now
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  	def all
    	user = User.from_omniauth(request.env["omniauth.auth"])
    	if user.persisted?
      		flash.notice = "Welcome back #{user.username}!"
      		sign_in_and_redirect user
    	else
      		session["devise.user_attributes"] = user.attributes
      		redirect_to new_user_registration_url
    	end
  	end
  	alias_method :twitter, :all
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

	def index 
		@collections = Collection.all
	end

	def show 
		@clink = CollectionLink.new
		@collection = Collection.find(params[:id])
		@collection_links = CollectionLink.where(collection_id: @collection.id)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	skip_before_filter :authenticate_user!, only: [:index]
	before_action :set_globals
	

	def index
		@events = Event.all
	end


	private

	def set_globals 
		@link = HelpfulLink.new
	  	@links = HelpfulLink.all
	  	@user = current_user unless current_user.blank?
	end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

	def index 
			
		@favourites = current_user.favourites
		@links = HelpfulLink.all

		@fav = Favourite.new
		@link = HelpfulLink.new
		@user = current_user
	end

	def new
		@fav = Favourite.new    
	end

	def create
		@fav = Favourite.new(fav_params)
		if @fav.save
			# RequestMailer.new_request_agents(@request, User.find(@request.user_id)).deliver
			flash[:notice] = "Added to favourites"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def destroy
		@fav.destroy
		respond_to do |format|
			format.html { redirect_to root_url }
			format.json { head :no_content }
		end
	end

	private

	# Never trust parameters from the scary internet, only allow the white list through.
	def fav_params
		params.require(:favourite).permit(:user_id, :helpful_link_id)
	end



end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	skip_before_filter :authenticate_user!, only: [:home, :about, :contact]
	
	def home 
		@resource ||= User.new
		@fav = Favourite.new
		@events = Event.all
		@clink = CollectionLink.new
		@links = HelpfulLink.all
		@link = HelpfulLink.new
	  	@user = current_user unless current_user.blank?
	  	@collections = Collection.all.limit(4)
		if signed_in?
			render :dashboard
		end
	end

	def dashboard
		redirect_to root_url
	end

	def about
	end

	def contact
	end

	def sitemap
	end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_globals

  def new
    super
  end

  def create
  	super
    # add custom create logic here
  end

  def show
  end

  def update
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end

  def set_globals 
    @link = HelpfulLink.new
    @links = HelpfulLink.all
    @user = current_user unless current_user.blank?
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_links_helper.rb
module CollectionLinksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/helpful_links_helper.rb
module HelpfulLinksHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/users_helper.rb
module UsersHelper

	def portrait(size)

	    # Twitter
	    # mini (24x24)                                                                  
	    # normal (48x48)                                            
	    # bigger (73x73)                                                
	    # original (variable width x variable height)

	    if self.image.include? "twimg"

	        # determine filetype        
	        case 
	        when self.image.downcase.include?(".jpeg")
	            filetype = ".jpeg"
	        when self.image.downcase.include?(".jpg")
	            filetype = ".jpg"
	        when self.image.downcase.include?(".gif")
	            filetype = ".gif"
	        when self.image.downcase.include?(".png")
	            filetype = ".png"
	        else
	            raise "Unable to read filetype of Twitter image for User ##{self.id}"
	        end

	        # return requested size
	        if size == "original"
	            return self.image
	        else
	            return self.image.gsub(filetype, "_#{size}#{filetype}")
	        end

	    end

	end

end

app/views/statics/about.html.erb
<%= render 'shared/global_meta_tags' %>

<h1>About</h1>
<hr>

<h2>How it started</h2>
<p>Code And Beers was a concept thought up by the team at <a href="https://1roof.com">1ROOF</a> who found themselves all wanting to learn how to code. 
There are LOADS of resources online (resource page coming soon…) where you can learn for free but staying disciplined and having a helping hand when you need one is what makes the real difference!</p>

<blockquote>
	<p>“When you don't create things, you become defined by your tastes rather than ability. Your tastes only narrow & exclude people. So create.” </p>
	<p>― <a href="http://www.goodreads.com/author/show/259157.Why_The_Lucky_Stiff">Why The Lucky Stiff</a></p>
</blockquote>

<h2>The Concept</h2>
<p>Code And Beers is a weekly meetup where you are <strong>not</strong> coming to a lesson/lecture/talk. You are entering a community of individuals who all want to teach themselves how to code. By all being in the same place, you can help each other and they can help you. 
We always have at least one full time developer in house to answer questions (we mix up the languages each week) and obviously.. BEER :)</p>

<hr>

<h3>Sound good? Join the newsletter and never miss an event :)</h3>

<%= render 'shared/mailchimp_form' %>

app/views/statics/contact.html.erb
<%= render 'shared/global_meta_tags' %>

<div class="contact-wrapper">

	<section>
		<%#= image_tag current_user.avatar %>
		<h1>Hey!</h1>
		<hr class="white">
		<p>We have just launched so we will soon set up a contact form. For now, feel free to tweet us <a href="http://twitter.com/codeandbeers_">@Codeandbeers_</a></p>
	</section>
	
</div>

app/views/statics/dashboard.html.erb
<%= render 'shared/global_meta_tags' %>

<div class="dashboard-wrapper">

	<section>
		<%#= image_tag current_user.avatar %>
		<h1>Hey <%= current_user.username %></h1>
		<% if current_user.favourites.count > 0 %>
			<!-- <i class="fa fa-star"></i> <%#= link_to "#{current_user.favourites.count} Favourites", user_favourites_path(current_user) %> -->
		<% end %>
		<hr class="white">
	</section>
	
	<% unless @collections.blank? %>
		<section>
			<div class="">
				<h3><i class="fa fa-th"></i> Top Collections <%= link_to "View all", collections_path, class: "new_link" %></h3>
				<div class="collection-wrapper">
						<%= render 'collections/collection_list' %>
				</div>
			</div>
		</section>
	<% end %>

	<section>
		<div class="link-wrapper">
			<h3><i class="fa fa-list"></i> Latest Resources <%= link_to "+ Add new", "", class: "new_link", :data => {toggle: "modal", target: "#linkModal"} %></h3>
				<%= render partial: 'helpful_links/latest_resources'%>
				
				<%#= render 'helpful_links/links_list', locals: { collection_link: @collection_link} %>

		</div>
	</section>

</div>
 
<!-- Link Modal -->
<% if signed_in? %>
	<%= render 'shared/helpful_link_modal' %>
<% end %>

app/views/statics/home.html.erb
<%= render 'shared/global_meta_tags' %>

<div class="home-wrapper">

	<section>
		
	</section>
	<section>
	
			<div class="col-md-7">
				<h1 class="headline" >Welcome to Code And Beers!</h1>
				<hr class="grey">
				<p class="description">We run <a href="/events">weekly meetups</a> for people who want to learn how to code, or just want to improve! There is no limit to how good you need to be, we always have full time developers on site to lend a hand and we also drink <strong>BEER</strong> (No worries if you don't drink beer, we have plenty other drinks)! <a href="/about">Find out more...</a></p>
				<hr>

				<div class="event-wrapper">
					<div class="event-link-wrapper">	

						<h3>Next Events</h3>
						<% @events.future.limit(3).each do |e| %>
							<div class="well">
								<div class="row">
									<div class="col-md-2">
										<%= image_tag e.image, id: "image", style: "margin-left: auto; margin-right: auto;" %>
									</div>
									<div class="col-md-10">
										<strong><%= e.name %></strong>
										<span id="date"><h5><em><%= e.date.strftime("%A, #{e.date.day.ordinalize} %B") %> <%= e.time_start.strftime("%H:%M") %> - <%= e.time_end.strftime("%H:%M") %></em></h5></span>
										<%= link_to "Get Tickets", e.ticket_link %> | <%= link_to "Find Out More", "", :data => {toggle: "modal", target: "#eventModal#{e.id}"} %>
									</div>
								</div>
							</div>

							<%# unless Event.where(id: e.id).blank? %>
								<%#= render 'shared/event_modal', locals: { event: Event.find(e.id) } %>
							<%# end %>

							<!-- Event Modal -->
							<div class="event-modal-wrapper">
				              	<div class="modal fade" id="eventModal<%=e.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				                	<div class="modal-dialog">
				                  		<div class="modal-content">
				                    		<div class="modal-header">
				                      			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				                      			<div class="row">
				                      				<div class="col-md-3">
            						  					<h4 class="modal-title header-image" id="myModalLabel"><%= image_tag e.image %></h4>
            						  				</div>
				                      				<div class="col-md-9">
				                      					<h4 class="modal-title" id="myModalLabel"><strong><%=e.name%></strong></h4>
				                      					<span id="date"><h5><em><%= e.date.strftime("%A, #{e.date.day.ordinalize} %B") %> <%= e.time_start.strftime("%H:%M") %> - <%= e.time_end.strftime("%H:%M") %></em></h5></span>
				                      				</div>
				                      			</div>
				                    		</div>
			                    			<div class="modal-body">
				                    			<div class="row">
				                      				<div class="col-md-12">
				                    					<%= e.description.html_safe %>
				                    				</div>
				                    			</div>
				                    		</div>
				                    		<div class="modal-footer">
				                      			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				                      			<%= link_to "Get Tickets", e.ticket_link, class: "btn btn-success" %>
				                    		</div>
				                  		</div>
				                	</div>
				              	</div>
				            </div>


						<% end %>

						<%= link_to "View all events...", "/events" %>

					</div>
				</div>

				<hr>
				<h3>Never miss an event! Join our newsletter</h3>
				<%= render 'shared/mailchimp_form' %>



			</div>
			<div class="col-md-5">
            	<div class="join-wrapper">

						<h2 id="content_head">Join The Community</h2>
						<h4>Already a member? <%= link_to "Login Here", new_user_session_path %></h4>
						<%= link_to " Sign Up Via Twitter", user_omniauth_authorize_path(:twitter), class: "btn btn-twitter fa fa-twitter hover-rise", style: "margin-top: 10px; width: 100%; line-height: 35px;" %>
						<h3>Or sign up below:</h3>
						<div class="home-signup">
							<%= render 'devise/registrations/new_form' %>
						</div>

				</div>
			</div>

	</section>
</div>