config/routes.rb
Codeandbeers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => {:registrations => "users", :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    get 'users/:id' => 'users#show', as: "user"
  end
  resources :users do 
    resources :helpful_links  
    resources :favourites  
  end
  
  root 'statics#home'
  
  resources :statics
  resources :events
  resources :collections
  resources :collection_links


  #Match Routes
  match '/about' => 'statics#about', via: 'get', as: 'about'
  match '/contact' => 'statics#contact', via: 'get', as: 'contact'
  match '/dashboard' => 'statics#dashboard', via: 'get', as: 'dashboard'
  match '/sitemap' => 'statics#sitemap', via: 'get', as: 'sitemap'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/collection.rb
class Collection < ActiveRecord::Base

has_many :helpful_links, :through => :collection_links
has_many :collection_links

end

app/models/collection_link.rb
class CollectionLink < ActiveRecord::Base
belongs_to :helpful_link
belongs_to :collection
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :future, lambda { where("date >= ?", Date.today ) }
	scope :past, lambda { where("date < ?", Date.today ) }
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
belongs_to :user
belongs_to :helpful_link
end

app/models/helpful_link.rb
class HelpfulLink < ActiveRecord::Base
    
    # Associations
    belongs_to :user
    has_many :favourites
    has_many :collections, :through => :collection_links
	has_many :collection_links
    
    after_create :send_notification

    def send_notification
		AdminMailer.new_resource(self).deliver_now
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:twitter]

    has_many :helpful_links
    has_many :favourites
    after_create :send_notification

    validates_presence_of :username
    validates_uniqueness_of :username

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = auth.info.nickname
	    user.avatar = auth.info.image.sub("_normal", "")
	    # user.email = auth.info.email unless auth.info.email.blank?
	    # user.password = Devise.friendly_token[0,20]
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

	def send_notification
		AdminMailer.new_user(self).deliver_now
		UserMailer.new_user_welcome(self).deliver_now
	end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  	def all
    	user = User.from_omniauth(request.env["omniauth.auth"])
    	if user.persisted?
      		flash.notice = "Welcome back #{user.username}!"
      		sign_in_and_redirect user
    	else
      		session["devise.user_attributes"] = user.attributes
      		redirect_to new_user_registration_url
    	end
  	end
  	alias_method :twitter, :all
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	skip_before_filter :authenticate_user!, only: [:index]
	before_action :set_globals
	

	def index
		@events = Event.all
	end


	private

	def set_globals 
		@link = HelpfulLink.new
	  	@links = HelpfulLink.all
	  	@user = current_user unless current_user.blank?
	end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

	def index 
			
		@favourites = current_user.favourites
		@links = HelpfulLink.all

		@fav = Favourite.new
		@link = HelpfulLink.new
		@user = current_user
	end

	def new
		@fav = Favourite.new    
	end

	def create
		@fav = Favourite.new(fav_params)
		if @fav.save
			# RequestMailer.new_request_agents(@request, User.find(@request.user_id)).deliver
			flash[:notice] = "Added to favourites"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def destroy
		@fav.destroy
		respond_to do |format|
			format.html { redirect_to root_url }
			format.json { head :no_content }
		end
	end

	private

	# Never trust parameters from the scary internet, only allow the white list through.
	def fav_params
		params.require(:favourite).permit(:user_id, :helpful_link_id)
	end



end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	skip_before_filter :authenticate_user!, only: [:home, :about, :contact]
	
	def home 
		@resource ||= User.new
		@fav = Favourite.new
		@events = Event.all
		@clink = CollectionLink.new
		@links = HelpfulLink.all
		@link = HelpfulLink.new
	  	@user = current_user unless current_user.blank?
	  	@collections = Collection.all.limit(4)
		if signed_in?
			render :dashboard
		end
	end

	def dashboard
		redirect_to root_url
	end

	def about
	end

	def contact
	end

	def sitemap
	end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_globals

  def new
    super
  end

  def create
  	super
    # add custom create logic here
  end

  def show
  end

  def update
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end

  def set_globals 
    @link = HelpfulLink.new
    @links = HelpfulLink.all
    @user = current_user unless current_user.blank?
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_links_helper.rb
module CollectionLinksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/helpful_links_helper.rb
module HelpfulLinksHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/users_helper.rb
module UsersHelper

	def portrait(size)

	    # Twitter
	    # mini (24x24)                                                                  
	    # normal (48x48)                                            
	    # bigger (73x73)                                                
	    # original (variable width x variable height)

	    if self.image.include? "twimg"

	        # determine filetype        
	        case 
	        when self.image.downcase.include?(".jpeg")
	            filetype = ".jpeg"
	        when self.image.downcase.include?(".jpg")
	            filetype = ".jpg"
	        when self.image.downcase.include?(".gif")
	            filetype = ".gif"
	        when self.image.downcase.include?(".png")
	            filetype = ".png"
	        else
	            raise "Unable to read filetype of Twitter image for User ##{self.id}"
	        end

	        # return requested size
	        if size == "original"
	            return self.image
	        else
	            return self.image.gsub(filetype, "_#{size}#{filetype}")
	        end

	    end

	end

end

app/views/layouts/_footer.html.erb
<footer>
	&copy; Code And Beers <%= Time.now.year %>		
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag 'logo/logo.png', class: "main-logo" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_url, :class => 'navbar-link'  %></li>
        <li><%= link_to "About", root_url, :class => 'navbar-link'  %></li>
      <li><%= link_to "Blog", root_url, :class => 'navbar-link'  %></li>
      </ul>
   
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
			  <!-- <li>Logged in as <strong><%#= current_user.email %></strong></li> -->
			  <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
			  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
			<% else %>
				<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
			  	<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
			<% end %>
		</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <div class="site-info-wrapper">
            <div class="site-info">
                <div id="alert">
                    <% if notice %>
                      <p class="alert alert-success"><%= notice %></p>
                    <% end %>
                    <% if alert %>
                      <p class="alert alert-danger"><%= alert %></p>
                    <% end %>
                </div>
                <div id="logo">
                    <%= link_to image_tag('logo/logo.png', class: "main-logo"), root_url %>
                </div>
                <div id="content">
                    <h1>Code And Beers</h1>
                    <p>A community of individuals teaching themselves how to code...together</p>
                    <hr class="grey">
                </div>
                <div id="social">
                    <%= link_to "", "https://twitter.com/codeandbeers_", class: "fa fa-twitter" %>
                    <%= link_to "", "https://www.facebook.com/codeandbeers", class: "fa fa-facebook" %>
                    <%= link_to "", "mailto:#{GLOBALS_CONFIG['contact_email']}", class: "fa fa-envelope" %>
                </div>
            </div>
        </div>
        <% if signed_in? %>
            <div class="site-actions">
                <div class="col-xs-3 action" data-toggle="tooltip" data-placement="top" title="Slack Community">
                    <%= link_to "", "http://codeandbeers.slack.com", class: "btn btn-actn fa fa-slack action-icon", target: "blank" %>
                </div>
                <div class="col-xs-3 action" data-toggle="tooltip" data-placement="top" title="Events">
                    <%= link_to "", events_path, class: "btn btn-actn fa fa-calendar action-icon" %>
                </div>
                <div class="col-xs-3 action" data-toggle="tooltip" data-placement="top" title="Collections">
                    <%= link_to "", collections_path, class: "btn btn-actn fa fa-th action-icon" %>
                </div>
                <div class="col-xs-3 action end" data-toggle="tooltip" data-placement="top" title="Resources">
                    <%#= link_to "", "", class: "btn btn-actn fa fa-plus action-icon", :data => {toggle: "modal", target: "#linkModal"} %>
                    <%= link_to "", root_url, class: "btn btn-actn fa fa-list action-icon" %>
                </div>
            </div>
        <% end %>

        <div class="site-navbar">
            <!-- <li class="sidebar-brand">
                <a href="#">
                    Start Bootstrap
                </a>
            </li> -->
            <li>
                <%= link_to "Home", root_url, :class => 'navbar-link'  %>
            </li>
            <li>
                <%= link_to "About", "/about", :class => 'navbar-link'  %>
            </li>
            <li>
                <%= link_to "Events", "/events", :class => 'navbar-link' unless signed_in?  %>
            </li>
             <li>
                <%= link_to "Blog", "http://blog.codeandbeers.com", :class => 'navbar-link', target: "_blank"  %>
            </li>
            <li>
                <%= link_to "Contact", "/contact", :class => 'navbar-link'  %>
            </li>
        </div>
    </ul>
    
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/_user_menu.html.erb
<div class="user-menu-wrapper">
	<div class="dropdown">
		<a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
			<div class="user-menu-drop">

				<div id="content">
					<%= image_tag current_user.avatar unless current_user.avatar.blank? %>
					<%= image_tag 'icons/default_user.png' unless current_user.avatar %>
	 			</div>

	 		</div>
		</a>
		<ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
		<% if user_signed_in? %>
          <!-- <li>Logged in as <strong><%#= current_user.email %></strong></li> -->
          <li><%= link_to ' Edit profile', edit_user_registration_path, :class => 'fa fa-cog navbar-link' %></li>
          <li><%= link_to " Logout", destroy_user_session_path, method: :delete, :class => 'fa fa-sign-out navbar-link'  %></li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
	   
	  </ul>
	</div>

	<div class="fab blue">
      <core-icon icon="mail"></core-icon>
      <paper-ripple class="circle recenteringTouch" fit></paper-ripple>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>

		<!-- Meta Tags rendered from page -->
    	<%= display_meta_tags %>

    	<!-- Meta tag for responsive site -->
    	<meta name="viewport" content="width=device-width, initial-scale=1">

    	<!-- Google Analytics -->
    	<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-61816740-1', 'auto');
		  ga('send', 'pageview');

		</script>

	</head>
	<body>
		<%#= render 'layouts/header' %>
		<div class="wrap">
			<div id="wrapper">
				<%= render 'layouts/sidebar' %>
				<a href="#menu-toggle" class="fa fa-bars menu-bars" id="menu-toggle"></a>
				<div id="page-content-wrapper">
		            <div class="container-fluid">
		                <div class="row">
		                	<% if signed_in? %>
		                		<%= render 'layouts/user_menu' %>
		                	<% end %>
							<%= yield %>
						</div>
					</div>
				</div>
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>

    <script>
    	// Menu Toggle
	    $("#menu-toggle").click(function(e) {
	        e.preventDefault();
	        $("#wrapper").toggleClass("toggled");
	    });
	    // Toggle Tooltip
	    $(function () {
		  $('[data-toggle="tooltip"]').tooltip()
		})
    </script>

</html>

app/views/shared/_event_modal.html.erb
<% @event = locals[:event] %>

<div class="well">
  <div class="row">
    <div class="col-md-2 center">
      <%= link_to image_tag(@event.image, id: "image", style: "margin-left: auto; margin-right: auto;"), @event.ticket_link %>
    </div>
    <div class="col-md-8" id="header">
      <h4><strong><%= link_to @event.name, @event.ticket_link unless @event.date < Date.today %><%= @event.name unless @event.date >= Date.today %></strong></h4>
      <span id="date"><h5><em><%= @event.date.strftime("%A, #{@event.date.day.ordinalize} %B") %> <%= @event.time_start.strftime("%H:%M") %> - <%= @event.time_end.strftime("%H:%M") %></em></h5></span>
    </div>
    <div class="col-md-2">
    <%= link_to "Get Tickets", @event.ticket_link, class: "btn btn-success" unless @event.date < Date.today %>
    <%= link_to "Sold OUT", @event.ticket_link, class: "btn btn-success disabled" unless @event.date >= Date.today %>

    </div>
  </div>
  <div class="row">
    <div class="col-sm-12>">
      <hr>
      <p id="description"><%= @event.description.html_safe %></p>
    </div>
  </div>
</div>

app/views/shared/_global_meta_tags.html.erb
<% set_meta_tags :title => 'Code And Beers',
                 :description => 'A community of individuals teaching themselves how to code...together',
                 :keywords => 'Code, Tech, Beers, Development, HTML, CSS, Javascript, London, Startup, Coding, Web Development',
                 :url => 'https://www.codeandbeers.com',
                 :og => { 
                    :title => 'Code And Beers', 
                    :type => 'website',
                    :url => 'https://www.codeandbeers.com',
                    :image => {
                        :_      => "http://codeandbeers.com/assets/logo/logo.png",
                        :secure_url  => 'https://codeandbeers.com/assets/logo/logo.png'
                    },
                    :description => 'A community of individuals teaching themselves how to code...together' },
                 :twitter => { 
                    :card => 'summary',
                    :site => '@codeandbeers_',
                    :title => 'Code And Beers',
                    :description => 'A community of individuals teaching themselves how to code...together',
                    :image => 'http://codeandbeers.com/assets/logo/logo.png',
                    :url => 'https://codeandbeers.com' 
                    } %>
                    

app/views/shared/_helpful_link_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="linkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">New Resource</h3>
        <p class="muted"><em>Adding a resource is a great way to help out the communtiy! Thanks!</em></p>
      </div>
      <div class="modal-body">
		    <%= render 'helpful_links/new_form'%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_link_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="linkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">New Resource</h3>
        <p class="muted"><em>Adding a resource is a great way to help out the communtiy! Thanks!</em></p>
      </div>
      <div class="modal-body">
		    <%= render 'helpful_links/new_form'%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mailchimp_form.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<form action="//codeandbeers.us10.list-manage.com/subscribe/post?u=4b909a3b7e87d0d93fe8362c2&amp;id=412054486f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_4b909a3b7e87d0d93fe8362c2_412054486f" tabindex="-1" value=""></div>
	<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-CB">
    </div>
</form>
<!--End mc_embed_signup-->

app/views/shared/_user_modal.html.erb
<% @user = locals[:user] %>
<div class="user-modal-wrapper">
  <!-- User Show Modal -->
  <div class="modal fade" id="userModel<%=@user.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title header-image" id="myModalLabel"><%= image_tag @user.avatar %></h2>
            <h2 class="modal-title header-name" id="myModalLabel"><%= @user.username %></h2>
        </div>
        <div class="modal-body">
            <p>Member since: <strong><%= @user.created_at.strftime("#{@user.created_at.day.ordinalize} %B %Y") %></strong></p>
            <p>Links Submitted: <strong><%= @user.helpful_links.count %></strong></p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>  
      </div>
    </div>
  </div>
</div>